### ISSUE TITLE
Cant get it running

### ISSUE THREAD

**Issue by Overtorment** [karanjthakkar/showmyprs.com#12]
Just cloned it, maybe Im doing smth wrong, first time Go user :-)

```
burn@laptop2:~/go/src/github.com/karanjthakkar/showmyprs.com$ go build
# github.com/karanjthakkar/showmyprs.com
./main.go:103: not enough arguments in call to client.Search.Issues
        have (string, *github.SearchOptions)
        want ("context".Context, string, *github.SearchOptions)
./main.go:125: not enough arguments in call to client.Repositories.Get
        have (string, string)
        want ("context".Context, string, string)
./main.go:144: not enough arguments in call to client.PullRequests.IsMerged
        have (string, string, int)
        want ("context".Context, string, string, int)
```

**Comment by shurcooL** [comment]
@Overtorment You are not doing anything wrong, this is a valid issue. It's easy to fix.

The API the `github.com/google/go-github/github` package that this Go package uses has recently changed in https://github.com/google/go-github/pull/529. Since @karanjthakkar hasn't vendored a specific version of go-github, it defaults to using the latest, and so this package needs to be updated for that new API.

It's very easy, just a matter of adding `context.Context` first parameter to all go-github method calls. It's described in full detail in the commit message of https://github.com/google/go-github/commit/23d6cb9cacb5aa314e93d600fe20a48496a718d4.

@karanjthakkar, let me know if you have any questions about it, I can help. In fact, anyone can make a PR (no pun intended, hehe) that updates the API. :)

**Comment by karanjthakkar** [comment]
@shurcooL Ahh, I was following the discussion for that issue but didnt realise that I would need to add support for that 🙈 I'll push a PR fixing this soon.

@Overtorment Sorry about the confusion!
